- name: Manjaro Sway Desktop Setup
  hosts: localhost
  vars:
    configs:
      - { src: "sway/config.conf", dest: "~/.config/sway/config.d/config.conf" }
      - { src: "sway/definitions.conf", dest: "~/.config/sway/definitions.d/definitions.conf" }
      - { src: "rofi/config.rasi", dest: "~/.config/rofi/config.rasi" }
      - { src: "waybar/config.jsonc", dest: "~/.config/waybar/config.jsonc" }
      - { src: "broot/conf.hjson", dest: "~/.config/broot/conf.hjson" }
  tasks:
  - name: pacman Upgrade
    become: yes
    pacman:
      update_cache: yes
      upgrade: yes
  - name: Install packages
    become: yes
    pacman:
      name:
        - keepassxc
        - docker
        - broot
        - rustup
        - wireshark-qt
      state: present
  - name: Install aur packages
    shell:
      cmd: yay --noconfirm --needed -Sy {{ item }}
    register: out
    changed_when: out.rc != 0
    loop:
      - insomnia
      - visual-studio-code-bin
      - anki
      - extra/intellij-idea-community-edition
  - name: Download configs
    get_url:
      url: "https://raw.githubusercontent.com/felixkroemer/dotfiles/main/{{ item.src }}"
      dest: "{{ item.dest }}"
    loop: "{{ configs }}"
  - name: Enable Docker service
    become: yes
    systemd_service:
        name: docker
        enabled: yes
  - name: Add user to docker group
    become: yes
    user:
      name: felix
      groups: docker
      append: yes
